"""Excel / PDF / CSV export generation (Product Spec §4.4, §12.1, §12.2).

Watermarking is derived only from organisations.subscription_tier (== \"free\"),
never from a free-floating boolean. Export files are uploaded under the
exports/ prefix and tagged retention=export-30d. Actual 30-day deletion is a
bucket lifecycle rule configured by backend/scripts/configure_s3_lifecycle.py
(see docs/runbooks/deployment.md) — not put_object(Expires=...), which is only
an HTTP caching hint. Statement data stays in Postgres; regenerate after expiry.
"""

from __future__ import annotations

import csv
import io
import logging
import uuid
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from typing import Literal, Protocol, Sequence

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from app.config import settings
from app.schemas.risk import RiskFlagRecord
from app.schemas.variance import VarianceAnalysisResult
from app.services.mapper import MappingResult
from app.services.statements import StatementLineItemRecord

logger = logging.getLogger(__name__)

ExportFormat = Literal["xlsx", "csv", "pdf"]

# Product Spec §12.1 / user-facing pack disclaimer — required on every export.
DISCLAIMER_TEXT = (
    "Prepared for internal review and analysis. Not a statutory financial "
    "statement and not intended for regulatory filing."
)
WATERMARK_TEXT = "Generated by FinDraft"
EXPORT_PREFIX = "exports/"


_R2_JURISDICTIONS = frozenset({"wnam", "enam", "weur", "eeur", "apac", "oc", "auto"})


def _storage_is_r2() -> bool:
    """Cloudflare R2 does not implement S3 object tagging on PutObject."""
    url = settings.normalized_s3_endpoint_url() or ""
    return "r2.cloudflarestorage.com" in url


def _s3_client_region() -> str:
    """R2 rejects AWS region names (e.g. eu-west-1); use a jurisdiction or auto."""
    if _storage_is_r2():
        if settings.s3_region in _R2_JURISDICTIONS:
            return settings.s3_region
        return "auto"
    return settings.s3_region

_HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
_HEADER_FONT = Font(color="FFFFFF", bold=True)
_BRAND_FONT = Font(name="Calibri", size=14, bold=True)
_DISCLAIMER_FONT = Font(name="Calibri", size=9, italic=True, color="666666")
_WATERMARK_FONT = Font(name="Calibri", size=20, bold=True, color="DDDDDD")
_MONEY_FORMAT_GBP_USD = "#,##0.00"
# # ### ##0.00 — space-separated thousands that render correctly in Excel/LibreOffice
# (# ##0.00 only groups as "1234 567", missing the separator after the first digit group)
_MONEY_FORMAT_EUR = "# ### ##0.00"

_CURRENCY_SYMBOLS: dict[str, str] = {
    "GBP": "£",
    "USD": "$",
    "EUR": "€",
}


def format_currency(amount: Decimal, currency_code: str) -> str:
    """Format monetary amounts per Cursor Rules §10.7 (comma GBP/USD, space EUR)."""
    code = currency_code.upper()
    quantized = amount.quantize(Decimal("0.01"))
    sign = "-" if quantized < 0 else ""
    abs_val = abs(quantized)
    whole, _, frac = f"{abs_val:.2f}".partition(".")
    groups: list[str] = []
    digits = whole
    while digits:
        groups.insert(0, digits[-3:])
        digits = digits[:-3]
    separator = " " if code == "EUR" else ","
    int_part = separator.join(groups)
    symbol = _CURRENCY_SYMBOLS.get(code, code)
    return f"{sign}{symbol}{int_part}.{frac}"


def _money_number_format(currency_code: str) -> str:
    return (
        _MONEY_FORMAT_EUR
        if currency_code.upper() == "EUR"
        else _MONEY_FORMAT_GBP_USD
    )


class OrganisationTier(Protocol):
    """Minimal organisations-table shape for watermark decisions."""

    subscription_tier: str


@dataclass(frozen=True)
class ExportBranding:
    client_name: str
    period_end: date
    generated_at: datetime
    functional_currency: str = "GBP"
    organisation_name: str = ""


@dataclass(frozen=True)
class ExportPackage:
    """Already-built statement / variance / risk / mapping outputs."""

    sopl: Sequence[StatementLineItemRecord]
    sofp: Sequence[StatementLineItemRecord]
    socie: Sequence[StatementLineItemRecord]
    variance: VarianceAnalysisResult | None
    risk_flags: Sequence[RiskFlagRecord]
    mappings: Sequence[MappingResult]


@dataclass(frozen=True)
class BuiltExport:
    content: bytes
    content_type: str
    filename: str


class ObjectStorage(Protocol):
    def put_export(
        self,
        *,
        key: str,
        body: bytes,
        content_type: str,
        expires_at: datetime,
    ) -> None: ...

    def generate_signed_url(self, *, key: str, expires_in: int) -> str: ...

    def object_exists(self, *, key: str) -> bool: ...


def tier_requires_watermark(organisation: OrganisationTier) -> bool:
    """Free tier only — read from organisations.subscription_tier (§4.4 / §13.1)."""
    return organisation.subscription_tier == "free"


def build_export(
    format: ExportFormat,
    *,
    branding: ExportBranding,
    package: ExportPackage,
    organisation: OrganisationTier,
) -> BuiltExport:
    """Build file bytes. Watermark follows organisation.subscription_tier only."""
    watermark = tier_requires_watermark(organisation)
    if format == "xlsx":
        content = build_excel(branding, package, organisation=organisation)
        return BuiltExport(
            content=content,
            content_type=(
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            ),
            filename=_filename(branding, "xlsx"),
        )
    if format == "csv":
        content = build_csv(branding, package)
        return BuiltExport(
            content=content,
            content_type="text/csv; charset=utf-8",
            filename=_filename(branding, "csv"),
        )
    if format == "pdf":
        content = build_pdf(branding, package, organisation=organisation)
        return BuiltExport(
            content=content,
            content_type="application/pdf",
            filename=_filename(branding, "pdf"),
        )
    raise ValueError(f"Unsupported export format: {format!r}")


def build_excel(
    branding: ExportBranding,
    package: ExportPackage,
    *,
    organisation: OrganisationTier,
) -> bytes:
    """Multi-sheet workbook; monetary cells are Decimal values (not float)."""
    watermark = tier_requires_watermark(organisation)
    workbook = Workbook()
    # Remove default sheet; recreate in fixed order.
    default = workbook.active
    workbook.remove(default)

    _write_statement_sheet(workbook, "SOPL", branding, package.sopl, watermark)
    _write_statement_sheet(workbook, "SOFP", branding, package.sofp, watermark)
    _write_statement_sheet(workbook, "SOCIE", branding, package.socie, watermark)
    _write_variance_sheet(workbook, branding, package.variance, watermark)
    _write_risk_sheet(workbook, branding, package.risk_flags, watermark)
    _write_mapping_sheet(workbook, branding, package.mappings, watermark)

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def build_csv(branding: ExportBranding, package: ExportPackage) -> bytes:
    """Flat CSV of all statement line items with metadata + disclaimer header."""
    buffer = io.StringIO()
    buffer.write(f"# DISCLAIMER: {DISCLAIMER_TEXT}\n")
    buffer.write(
        f"# Client: {branding.client_name} | Period end: {branding.period_end.isoformat()} "
        f"| Generated: {branding.generated_at.date().isoformat()} "
        f"| Currency: {branding.functional_currency.upper()}\n"
    )
    writer = csv.writer(buffer)
    writer.writerow(
        [
            "statement_type",
            "line_item_code",
            "line_item_name",
            "amount",
            "is_subtotal",
            "display_order",
            "client_name",
            "period_end",
            "generated_at",
        ]
    )
    for statement_type, lines in (
        ("SOPL", package.sopl),
        ("SOFP", package.sofp),
        ("SOCIE", package.socie),
    ):
        for line in lines:
            writer.writerow(
                [
                    statement_type,
                    line.line_item_code,
                    line.line_item_name,
                    format_currency(line.amount, branding.functional_currency),
                    "true" if line.is_subtotal else "false",
                    line.display_order,
                    branding.client_name,
                    branding.period_end.isoformat(),
                    branding.generated_at.isoformat(),
                ]
            )
    return buffer.getvalue().encode("utf-8")


def build_pdf(
    branding: ExportBranding,
    package: ExportPackage,
    *,
    organisation: OrganisationTier,
) -> bytes:
    """Board-ready PDF via WeasyPrint. Free tier gets a FinDraft watermark."""
    from weasyprint import HTML

    html = render_pdf_html(
        branding,
        package,
        organisation=organisation,
    )
    return HTML(string=html).write_pdf()


def render_pdf_html(
    branding: ExportBranding,
    package: ExportPackage,
    *,
    organisation: OrganisationTier,
) -> str:
    """HTML source for the PDF pack (tested directly for disclaimer/watermark)."""
    watermark = tier_requires_watermark(organisation)
    watermark_css = ""
    watermark_div = ""
    if watermark:
        watermark_css = """
        .watermark {
          position: fixed; top: 40%; left: 10%; right: 10%;
          text-align: center; font-size: 42px; color: rgba(0,0,0,0.12);
          transform: rotate(-30deg); z-index: 0; pointer-events: none;
        }
        """
        watermark_div = f'<div class="watermark">{WATERMARK_TEXT}</div>'

    sections = [
        ("Statement of Profit or Loss", package.sopl),
        ("Statement of Financial Position", package.sofp),
        ("Statement of Changes in Equity", package.socie),
    ]
    toc_items = "".join(
        f"<li>{title}</li>" for title, _ in sections
    ) + "<li>Variance Analysis</li><li>Risk Flags</li><li>Mapping Summary</li>"

    body_sections: list[str] = []
    for title, lines in sections:
        currency_label = branding.functional_currency.upper()
        rows = "".join(
            "<tr>"
            f"<td>{_html_escape(line.line_item_name)}</td>"
            f"<td class='num'>{_html_escape(format_currency(line.amount, branding.functional_currency))}</td>"
            "</tr>"
            for line in lines
        )
        body_sections.append(
            f"<section><h2>{_html_escape(title)}</h2>"
            f"<p>All amounts in <strong>{currency_label}</strong></p>"
            f"<table><thead><tr><th>Line</th><th>Amount</th></tr></thead>"
            f"<tbody>{rows}</tbody></table></section>"
        )

    variance_rows = ""
    if package.variance is not None:
        for item in package.variance.items:
            pct = item.variance_pct if item.variance_pct is not None else "n/a"
            variance_rows += (
                "<tr>"
                f"<td>{_html_escape(item.line_item_name)}</td>"
                f"<td class='num'>{item.current_amount}</td>"
                f"<td class='num'>{item.prior_amount}</td>"
                f"<td class='num'>{item.variance_amount}</td>"
                f"<td>{pct}</td>"
                f"<td>{item.direction}</td>"
                f"<td>{'Yes' if item.is_material else 'No'}</td>"
                "</tr>"
            )
    body_sections.append(
        "<section><h2>Variance Analysis</h2>"
        "<table><thead><tr>"
        "<th>Line</th><th>Current</th><th>Prior</th><th>Variance</th>"
        "<th>%</th><th>Direction</th><th>Material</th>"
        f"</tr></thead><tbody>{variance_rows}</tbody></table></section>"
    )

    risk_rows = "".join(
        "<tr>"
        f"<td>{_html_escape(flag.rule_name)}</td>"
        f"<td>{flag.severity}</td>"
        f"<td>{_html_escape(flag.description)}</td>"
        "</tr>"
        for flag in package.risk_flags
    )
    body_sections.append(
        "<section><h2>Risk Flags</h2>"
        "<table><thead><tr><th>Rule</th><th>Severity</th><th>Description</th></tr></thead>"
        f"<tbody>{risk_rows}</tbody></table></section>"
    )

    mapping_rows = "".join(
        "<tr>"
        f"<td>{_html_escape(row.source_code)}</td>"
        f"<td>{_html_escape(row.source_name)}</td>"
        f"<td>{_html_escape(row.canonical_line or '')}</td>"
        f"<td>{_html_escape(row.method or '')}</td>"
        f"<td>{_money_str(row.confidence) if row.confidence is not None else ''}</td>"
        "</tr>"
        for row in package.mappings
    )
    body_sections.append(
        "<section><h2>Mapping Summary</h2>"
        "<table><thead><tr>"
        "<th>Code</th><th>Name</th><th>Canonical</th><th>Method</th><th>Confidence</th>"
        f"</tr></thead><tbody>{mapping_rows}</tbody></table></section>"
    )

    org_line = (
        f"<p><strong>Organisation:</strong> {_html_escape(branding.organisation_name)}</p>"
        if branding.organisation_name
        else ""
    )

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<style>
  body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #222; }}
  h1 {{ font-size: 22px; }} h2 {{ font-size: 16px; margin-top: 24px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
  th, td {{ border-bottom: 1px solid #ddd; padding: 4px 6px; text-align: left; }}
  td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .disclaimer {{ margin-top: 24px; padding: 12px; border: 1px solid #999;
                 background: #f7f7f7; font-size: 10px; font-style: italic; }}
  .cover {{ page-break-after: always; }}
  {watermark_css}
</style></head><body>
{watermark_div}
<section class="cover">
  <h1>FinDraft Management Accounts Pack</h1>
  <p><strong>Client:</strong> {_html_escape(branding.client_name)}</p>
  {org_line}
  <p><strong>Period end:</strong> {branding.period_end.isoformat()}</p>
  <p><strong>Currency:</strong> {branding.functional_currency.upper()}</p>
  <p><strong>Generated:</strong> {branding.generated_at.isoformat()}</p>
  <div class="disclaimer"><strong>Disclaimer:</strong> {_html_escape(DISCLAIMER_TEXT)}</div>
  <h2>Contents</h2>
  <ol>{toc_items}</ol>
</section>
{"".join(body_sections)}
</body></html>"""


def export_object_key(export_id: uuid.UUID, format: ExportFormat) -> str:
    return f"{EXPORT_PREFIX}{export_id}.{format}"


def upload_export_file(
    storage: ObjectStorage,
    *,
    export_id: uuid.UUID,
    format: ExportFormat,
    built: BuiltExport,
) -> str:
    """Upload under exports/ and return a signed URL.

    Objects are tagged retention=export-30d so the bucket lifecycle rule from
    backend/scripts/configure_s3_lifecycle.py (docs/runbooks/deployment.md) can
    expire them after export_file_ttl_days. put_object Expires= is only an HTTP
    caching hint — it does not delete objects. Application code regenerates from
    retained statement data if a later download finds the object gone; it does
    not implement its own sweeper.
    """
    key = export_object_key(export_id, format)
    expires_at = datetime.now(timezone.utc) + timedelta(
        days=settings.export_file_ttl_days
    )
    storage.put_export(
        key=key,
        body=built.content,
        content_type=built.content_type,
        expires_at=expires_at,
    )
    return storage.generate_signed_url(
        key=key,
        expires_in=settings.export_signed_url_ttl_seconds,
    )


def mark_export_processing(export: ExportStatusTarget) -> None:
    export.status = "processing"
    export.error_message = None


def mark_export_complete(export: ExportStatusTarget, *, file_url: str) -> None:
    export.status = "complete"
    export.file_url = file_url
    export.error_message = None


def mark_export_failed(export: ExportStatusTarget, *, error_message: str) -> None:
    export.status = "failed"
    export.error_message = error_message


def run_export_job(
    export: ExportStatusTarget,
    *,
    format: ExportFormat,
    branding: ExportBranding,
    package: ExportPackage,
    organisation: OrganisationTier,
    storage: ObjectStorage,
    export_id: uuid.UUID,
) -> ExportStatusTarget:
    """pending → processing → complete|failed, including S3 upload."""
    mark_export_processing(export)
    try:
        built = build_export(
            format,
            branding=branding,
            package=package,
            organisation=organisation,
        )
        file_url = upload_export_file(
            storage,
            export_id=export_id,
            format=format,
            built=built,
        )
        mark_export_complete(export, file_url=file_url)
    except Exception as exc:
        logger.exception("Export job failed for %s", export_id)
        mark_export_failed(export, error_message=str(exc))
    return export


def regenerate_export_if_missing(
    export: ExportStatusTarget,
    *,
    format: ExportFormat,
    branding: ExportBranding,
    package: ExportPackage,
    organisation: OrganisationTier,
    storage: ObjectStorage,
    export_id: uuid.UUID,
) -> str:
    """If the 30-day object is gone, rebuild from retained statement data."""
    key = export_object_key(export_id, format)
    if storage.object_exists(key=key) and export.file_url:
        return storage.generate_signed_url(
            key=key,
            expires_in=settings.export_signed_url_ttl_seconds,
        )
    run_export_job(
        export,
        format=format,
        branding=branding,
        package=package,
        organisation=organisation,
        storage=storage,
        export_id=export_id,
    )
    if export.status != "complete" or not export.file_url:
        raise RuntimeError(export.error_message or "Export regeneration failed")
    return export.file_url


class ExportStatusTarget(Protocol):
    status: str
    file_url: str | None
    error_message: str | None


class S3ObjectStorage:
    """boto3-backed storage for S3 or Cloudflare R2."""

    def __init__(self, client: object | None = None) -> None:
        if client is not None:
            self._client = client
        else:
            import boto3

            kwargs: dict[str, object] = {"region_name": _s3_client_region()}
            endpoint = settings.normalized_s3_endpoint_url()
            if endpoint:
                kwargs["endpoint_url"] = endpoint
            if settings.aws_access_key_id and settings.aws_secret_access_key:
                kwargs["aws_access_key_id"] = settings.aws_access_key_id
                kwargs["aws_secret_access_key"] = settings.aws_secret_access_key
            self._client = boto3.client("s3", **kwargs)

    def put_export(
        self,
        *,
        key: str,
        body: bytes,
        content_type: str,
        expires_at: datetime,
    ) -> None:
        # Expires= → HTTP Expires response header only (caching hint). It does
        # NOT schedule object deletion. Tagging= feeds AWS S3 lifecycle filters;
        # R2 does not support x-amz-tagging on PutObject — use prefix-only
        # lifecycle on R2 (see configure_s3_lifecycle.py).
        put_kwargs: dict[str, object] = {
            "Bucket": settings.s3_bucket,
            "Key": key,
            "Body": body,
            "ContentType": content_type,
            "Expires": expires_at,
            "Metadata": {
                "export-ttl-days": str(settings.export_file_ttl_days),
            },
        }
        if not _storage_is_r2():
            put_kwargs["Tagging"] = "retention=export-30d"
        self._client.put_object(**put_kwargs)

    def generate_signed_url(self, *, key: str, expires_in: int) -> str:
        return self._client.generate_presigned_url(
            "get_object",
            Params={"Bucket": settings.s3_bucket, "Key": key},
            ExpiresIn=expires_in,
        )

    def object_exists(self, *, key: str) -> bool:
        try:
            self._client.head_object(Bucket=settings.s3_bucket, Key=key)
            return True
        except Exception:
            return False


# --- Excel helpers -----------------------------------------------------------


def _write_branding(
    ws: Worksheet,
    branding: ExportBranding,
    *,
    watermark: bool,
    start_row: int = 1,
) -> int:
    ws.cell(start_row, 1, branding.client_name).font = _BRAND_FONT
    ws.cell(start_row + 1, 1, f"Period end: {branding.period_end.isoformat()}")
    ws.cell(
        start_row + 2,
        1,
        f"All amounts in {branding.functional_currency.upper()}",
    )
    ws.cell(
        start_row + 3,
        1,
        f"Generated: {branding.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
    )
    if branding.organisation_name:
        ws.cell(start_row + 4, 1, f"Organisation: {branding.organisation_name}")
        next_row = start_row + 5
    else:
        next_row = start_row + 4
    if watermark:
        cell = ws.cell(next_row, 1, WATERMARK_TEXT)
        cell.font = _WATERMARK_FONT
        next_row += 1
    return next_row + 1


def _write_disclaimer(ws: Worksheet, row: int) -> int:
    cell = ws.cell(row, 1, DISCLAIMER_TEXT)
    cell.font = _DISCLAIMER_FONT
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=4)
    return row + 2


def _write_statement_sheet(
    workbook: Workbook,
    title: str,
    branding: ExportBranding,
    lines: Sequence[StatementLineItemRecord],
    watermark: bool,
) -> None:
    ws = workbook.create_sheet(title)
    row = _write_branding(ws, branding, watermark=watermark)
    row = _write_disclaimer(ws, row)
    ws.cell(row, 1, "Line item").font = _HEADER_FONT
    ws.cell(row, 1).fill = _HEADER_FILL
    ws.cell(row, 2, "Amount").font = _HEADER_FONT
    ws.cell(row, 2).fill = _HEADER_FILL
    ws.cell(row, 3, "Subtotal").font = _HEADER_FONT
    ws.cell(row, 3).fill = _HEADER_FILL
    row += 1
    money_format = _money_number_format(branding.functional_currency)
    for line in lines:
        ws.cell(row, 1, line.line_item_name)
        amount_cell = ws.cell(row, 2, _excel_money(line.amount))
        amount_cell.number_format = money_format
        amount_cell.alignment = Alignment(horizontal="right")
        ws.cell(row, 3, "Yes" if line.is_subtotal else "No")
        row += 1
    _autosize(ws, 3)


def _write_variance_sheet(
    workbook: Workbook,
    branding: ExportBranding,
    variance: VarianceAnalysisResult | None,
    watermark: bool,
) -> None:
    ws = workbook.create_sheet("Variance")
    row = _write_branding(ws, branding, watermark=watermark)
    row = _write_disclaimer(ws, row)
    headers = [
        "Line item",
        "Current",
        "Prior",
        "Variance",
        "Variance %",
        "Direction",
        "Material",
    ]
    for col, header in enumerate(headers, start=1):
        cell = ws.cell(row, col, header)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
    row += 1
    money_format = _money_number_format(branding.functional_currency)
    if variance is not None:
        for item in variance.items:
            ws.cell(row, 1, item.line_item_name)
            for col, raw in enumerate(
                (item.current_amount, item.prior_amount, item.variance_amount),
                start=2,
            ):
                cell = ws.cell(row, col, _excel_money(Decimal(raw)))
                cell.number_format = money_format
            ws.cell(
                row,
                5,
                item.variance_pct if item.variance_pct is not None else "",
            )
            ws.cell(row, 6, item.direction)
            ws.cell(row, 7, "Yes" if item.is_material else "No")
            row += 1
    _autosize(ws, 7)


def _write_risk_sheet(
    workbook: Workbook,
    branding: ExportBranding,
    flags: Sequence[RiskFlagRecord],
    watermark: bool,
) -> None:
    ws = workbook.create_sheet("Risk")
    row = _write_branding(ws, branding, watermark=watermark)
    row = _write_disclaimer(ws, row)
    for col, header in enumerate(
        ("Rule", "Severity", "Description", "Recommended action"), start=1
    ):
        cell = ws.cell(row, col, header)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
    row += 1
    for flag in flags:
        ws.cell(row, 1, flag.rule_name)
        ws.cell(row, 2, flag.severity)
        ws.cell(row, 3, flag.description)
        ws.cell(row, 4, flag.recommended_action or "")
        row += 1
    _autosize(ws, 4)


def _write_mapping_sheet(
    workbook: Workbook,
    branding: ExportBranding,
    mappings: Sequence[MappingResult],
    watermark: bool,
) -> None:
    ws = workbook.create_sheet("Mapping Summary")
    row = _write_branding(ws, branding, watermark=watermark)
    row = _write_disclaimer(ws, row)
    for col, header in enumerate(
        ("Code", "Name", "Canonical line", "Method", "Confidence"), start=1
    ):
        cell = ws.cell(row, col, header)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
    row += 1
    for mapping in mappings:
        ws.cell(row, 1, mapping.source_code)
        ws.cell(row, 2, mapping.source_name)
        ws.cell(row, 3, mapping.canonical_line or "")
        ws.cell(row, 4, mapping.method or "")
        if mapping.confidence is not None:
            cell = ws.cell(row, 5, _excel_money(mapping.confidence))
            cell.number_format = "0.00"
        else:
            ws.cell(row, 5, "")
        row += 1
    _autosize(ws, 5)


def _excel_money(amount: Decimal) -> Decimal:
    """Quantize for the sheet — returns Decimal, never float."""
    if not isinstance(amount, Decimal):
        raise TypeError(f"Excel money cells require Decimal, got {type(amount)!r}")
    return amount.quantize(Decimal("0.01"))


def _money_str(amount: Decimal) -> str:
    return f"{amount.quantize(Decimal('0.01'))}"


def _autosize(ws: Worksheet, columns: int) -> None:
    for index in range(1, columns + 1):
        letter = get_column_letter(index)
        max_length = 0
        for cell in ws[letter]:
            value = "" if cell.value is None else str(cell.value)
            max_length = max(max_length, len(value))
        ws.column_dimensions[letter].width = min(max_length + 2, 60)


def _filename(branding: ExportBranding, extension: str) -> str:
    safe = "".join(
        ch if ch.isalnum() or ch in ("-", "_") else "_"
        for ch in branding.client_name.strip()
    ) or "export"
    return f"{safe}_{branding.period_end.isoformat()}.{extension}"


def _html_escape(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
