"""initial schema

Revision ID: 5698f66e1e9c
Revises: 
Create Date: 2026-08-29 22:39:04.877040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5698f66e1e9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subscription_tier', sa.String(), server_default=sa.text("'free'"), nullable=False),
    sa.Column('subscription_status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('functional_currency', sa.String(length=3), server_default=sa.text("'GBP'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("subscription_status IN ('active', 'past_due', 'cancelled', 'trialing')", name='organisations_subscription_status_check'),
    sa.CheckConstraint("subscription_tier IN ('free', 'starter', 'pro', 'scale')", name='organisations_subscription_tier_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id')
    )
    op.create_index('idx_organisations_clerk_org_id', 'organisations', ['clerk_org_id'], unique=False)
    op.create_index('idx_organisations_stripe_customer', 'organisations', ['stripe_customer_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_number', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('functional_currency', sa.String(length=3), server_default=sa.text("'GBP'"), nullable=False),
    sa.Column('materiality_threshold_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('10.00'), nullable=False),
    sa.Column('materiality_threshold_abs', sa.Numeric(precision=19, scale=2), server_default=sa.text('1000.00'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_org_deleted', 'clients', ['org_id', 'is_deleted'], unique=False)
    op.create_index('idx_clients_org_id', 'clients', ['org_id'], unique=False)
    op.create_table('subscription_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index('idx_subscription_events_org', 'subscription_events', ['org_id'], unique=False)
    op.create_index('idx_subscription_events_stripe', 'subscription_events', ['stripe_event_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member', 'viewer')", name='users_role_check'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index('idx_users_clerk_user_id', 'users', ['clerk_user_id'], unique=False)
    op.create_index('idx_users_org_id', 'users', ['org_id'], unique=False)
    op.create_table('account_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('canonical_line', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('exact', 'fuzzy', 'code_range', 'llm', 'manual')", name='account_mappings_method_check'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'source_code', 'source_name', name='account_mappings_client_id_source_code_source_name_key')
    )
    op.create_index('idx_account_mappings_client_confirmed', 'account_mappings', ['client_id', 'is_confirmed'], unique=False)
    op.create_index('idx_account_mappings_client_id', 'account_mappings', ['client_id'], unique=False)
    op.create_table('archived_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('archive_reason', sa.String(), nullable=False),
    sa.Column('archived_by_user_id', sa.UUID(), nullable=True),
    sa.Column('archived_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archive_hash', sa.String(length=64), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_archived_records_entity', 'archived_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_archived_records_org', 'archived_records', ['org_id'], unique=False)
    op.create_index('idx_archived_records_retention', 'archived_records', ['retention_until'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('processing_complete', 'export_ready', 'validation_failed', 'llm_unavailable', 'billing_alert')", name='notifications_type_check'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('trial_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('xlsx', 'csv')", name='trial_balances_file_type_check'),
    sa.CheckConstraint("status IN ('pending', 'parsing', 'mapping', 'validating', 'generating', 'analysing', 'complete', 'failed')", name='trial_balances_status_check'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'period_end', name='trial_balances_client_id_period_end_key')
    )
    op.create_index('idx_trial_balances_client_id', 'trial_balances', ['client_id'], unique=False)
    op.create_index('idx_trial_balances_client_period', 'trial_balances', ['client_id', 'period_end'], unique=False)
    op.create_index('idx_trial_balances_status', 'trial_balances', ['status'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tb_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('xlsx', 'csv', 'pdf')", name='exports_format_check'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'complete', 'failed')", name='exports_status_check'),
    sa.ForeignKeyConstraint(['tb_id'], ['trial_balances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exports_status', 'exports', ['status'], unique=False)
    op.create_index('idx_exports_tb_id', 'exports', ['tb_id'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tb_id', sa.UUID(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("statement_type IN ('SOPL', 'SOFP', 'SOCIE')", name='financial_statements_statement_type_check'),
    sa.ForeignKeyConstraint(['tb_id'], ['trial_balances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_financial_statements_tb_id', 'financial_statements', ['tb_id'], unique=False)
    op.create_index('idx_financial_statements_tb_type', 'financial_statements', ['tb_id', 'statement_type'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tb_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('parse', 'map', 'validate', 'statements', 'variance', 'risk', 'export')", name='processing_jobs_job_type_check'),
    sa.CheckConstraint("status IN ('pending', 'running', 'complete', 'failed', 'retrying')", name='processing_jobs_status_check'),
    sa.CheckConstraint('progress_pct >= 0 AND progress_pct <= 100', name='processing_jobs_progress_pct_check'),
    sa.ForeignKeyConstraint(['tb_id'], ['trial_balances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('idx_processing_jobs_tb_id', 'processing_jobs', ['tb_id'], unique=False)
    op.create_table('risk_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tb_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('affected_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('warning', 'critical')", name='risk_flags_severity_check'),
    sa.ForeignKeyConstraint(['tb_id'], ['trial_balances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_flags_tb_id', 'risk_flags', ['tb_id'], unique=False)
    op.create_index('idx_risk_flags_tb_severity', 'risk_flags', ['tb_id', 'severity'], unique=False)
    op.create_table('variance_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tb_id', sa.UUID(), nullable=False),
    sa.Column('prior_tb_id', sa.UUID(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commentary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'generating', 'complete', 'failed')", name='variance_analyses_status_check'),
    sa.ForeignKeyConstraint(['prior_tb_id'], ['trial_balances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tb_id'], ['trial_balances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_variance_analyses_prior_tb', 'variance_analyses', ['prior_tb_id'], unique=False)
    op.create_index('idx_variance_analyses_tb_id', 'variance_analyses', ['tb_id'], unique=False)
    op.create_table('commentary_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('line_item_code', sa.String(), nullable=False),
    sa.Column('thumbs_up', sa.Boolean(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variance_id'], ['variance_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentary_feedback_user_id'), 'commentary_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_commentary_feedback_variance_id'), 'commentary_feedback', ['variance_id'], unique=False)
    op.create_table('statement_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('line_item_code', sa.String(), nullable=False),
    sa.Column('line_item_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('is_subtotal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('overridden_by_user_id', sa.UUID(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=19, scale=2), nullable=True),
    sa.Column('source_account_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['overridden_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['financial_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_statement_line_items_source_accounts', 'statement_line_items', ['source_account_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_statement_line_items_statement_id', 'statement_line_items', ['statement_id'], unique=False)
    # ### end Alembic commands ###

    # --- enforce_tb_balance trigger (Product Spec §9.1, v3.2 corrected) ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION enforce_tb_balance()
        RETURNS TRIGGER AS $$
        DECLARE
          blocking_checks TEXT[] := ARRAY['tb_integrity', 'balance_sheet_balance', 'net_assets'];
          check_name TEXT;
          check_failed BOOLEAN;
        BEGIN
          IF NEW.status = 'complete' AND NEW.validation_results IS NOT NULL THEN
            FOREACH check_name IN ARRAY blocking_checks LOOP
              SELECT EXISTS (
                SELECT 1 FROM jsonb_array_elements(NEW.validation_results->'checks') AS c
                WHERE c->>'check_name' = check_name AND (c->>'passed')::boolean = FALSE
              ) INTO check_failed;

              IF check_failed THEN
                RAISE EXCEPTION 'Cannot mark trial balance complete: % check failed.', check_name;
              END IF;
            END LOOP;
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_enforce_tb_balance
          BEFORE UPDATE ON trial_balances
          FOR EACH ROW
          EXECUTE FUNCTION enforce_tb_balance();
        """
    )

    # --- Row-Level Security policies (Product Spec §9.2) ---

    # Direct org_id column (simple policy)
    for table in ("clients", "audit_logs", "notifications", "archived_records"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_org_isolation ON {table}
              FOR ALL
              USING (org_id = current_setting('app.current_org_id')::UUID)
            """
        )

    # One join from org_id (trial_balances, account_mappings)
    op.execute("ALTER TABLE trial_balances ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY trial_balances_org_isolation ON trial_balances
          FOR ALL
          USING (
            client_id IN (
              SELECT id FROM clients
              WHERE org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )
    op.execute("ALTER TABLE account_mappings ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY account_mappings_org_isolation ON account_mappings
          FOR ALL
          USING (
            client_id IN (
              SELECT id FROM clients
              WHERE org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )

    # Two or three joins from org_id (financial_statements, variance_analyses, risk_flags, exports)
    op.execute("ALTER TABLE financial_statements ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY financial_statements_org_isolation ON financial_statements
          FOR ALL
          USING (
            tb_id IN (
              SELECT tb.id FROM trial_balances tb
              JOIN clients c ON tb.client_id = c.id
              WHERE c.org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )
    op.execute("ALTER TABLE variance_analyses ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY variance_analyses_org_isolation ON variance_analyses
          FOR ALL
          USING (
            tb_id IN (
              SELECT tb.id FROM trial_balances tb
              JOIN clients c ON tb.client_id = c.id
              WHERE c.org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )
    op.execute("ALTER TABLE risk_flags ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY risk_flags_org_isolation ON risk_flags
          FOR ALL
          USING (
            tb_id IN (
              SELECT tb.id FROM trial_balances tb
              JOIN clients c ON tb.client_id = c.id
              WHERE c.org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )
    op.execute("ALTER TABLE exports ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY exports_org_isolation ON exports
          FOR ALL
          USING (
            tb_id IN (
              SELECT tb.id FROM trial_balances tb
              JOIN clients c ON tb.client_id = c.id
              WHERE c.org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )

    # statement_line_items: three joins via statement_id -> financial_statements
    op.execute("ALTER TABLE statement_line_items ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY statement_line_items_org_isolation ON statement_line_items
          FOR ALL
          USING (
            statement_id IN (
              SELECT fs.id FROM financial_statements fs
              JOIN trial_balances tb ON fs.tb_id = tb.id
              JOIN clients c ON tb.client_id = c.id
              WHERE c.org_id = current_setting('app.current_org_id')::UUID
            )
          )
        """
    )


def downgrade() -> None:
    # --- Drop RLS policies (Product Spec §9.2) ---
    rls_tables = (
        "statement_line_items",
        "exports",
        "risk_flags",
        "variance_analyses",
        "financial_statements",
        "account_mappings",
        "trial_balances",
        "archived_records",
        "notifications",
        "audit_logs",
        "clients",
    )
    for table in rls_tables:
        op.execute(f"DROP POLICY IF EXISTS {table}_org_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # --- Drop enforce_tb_balance trigger and function ---
    op.execute("DROP TRIGGER IF EXISTS trg_enforce_tb_balance ON trial_balances")
    op.execute("DROP FUNCTION IF EXISTS enforce_tb_balance()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_statement_line_items_statement_id', table_name='statement_line_items')
    op.drop_index('idx_statement_line_items_source_accounts', table_name='statement_line_items', postgresql_using='gin')
    op.drop_table('statement_line_items')
    op.drop_index(op.f('ix_commentary_feedback_variance_id'), table_name='commentary_feedback')
    op.drop_index(op.f('ix_commentary_feedback_user_id'), table_name='commentary_feedback')
    op.drop_table('commentary_feedback')
    op.drop_index('idx_variance_analyses_tb_id', table_name='variance_analyses')
    op.drop_index('idx_variance_analyses_prior_tb', table_name='variance_analyses')
    op.drop_table('variance_analyses')
    op.drop_index('idx_risk_flags_tb_severity', table_name='risk_flags')
    op.drop_index('idx_risk_flags_tb_id', table_name='risk_flags')
    op.drop_table('risk_flags')
    op.drop_index('idx_processing_jobs_tb_id', table_name='processing_jobs')
    op.drop_index('idx_processing_jobs_status', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('idx_financial_statements_tb_type', table_name='financial_statements')
    op.drop_index('idx_financial_statements_tb_id', table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index('idx_exports_tb_id', table_name='exports')
    op.drop_index('idx_exports_status', table_name='exports')
    op.drop_table('exports')
    op.drop_index('idx_trial_balances_status', table_name='trial_balances')
    op.drop_index('idx_trial_balances_client_period', table_name='trial_balances')
    op.drop_index('idx_trial_balances_client_id', table_name='trial_balances')
    op.drop_table('trial_balances')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_audit_logs_org_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_archived_records_retention', table_name='archived_records')
    op.drop_index('idx_archived_records_org', table_name='archived_records')
    op.drop_index('idx_archived_records_entity', table_name='archived_records')
    op.drop_table('archived_records')
    op.drop_index('idx_account_mappings_client_id', table_name='account_mappings')
    op.drop_index('idx_account_mappings_client_confirmed', table_name='account_mappings')
    op.drop_table('account_mappings')
    op.drop_index('idx_users_org_id', table_name='users')
    op.drop_index('idx_users_clerk_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_subscription_events_stripe', table_name='subscription_events')
    op.drop_index('idx_subscription_events_org', table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index('idx_clients_org_id', table_name='clients')
    op.drop_index('idx_clients_org_deleted', table_name='clients')
    op.drop_table('clients')
    op.drop_index('idx_organisations_stripe_customer', table_name='organisations')
    op.drop_index('idx_organisations_clerk_org_id', table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
