"""Canonical line definitions and keywords. Implementation pending."""

CANONICAL_LINES: list[str] = [
    "revenue",
    "cost_of_sales",
    "gross_profit",
    "operating_expenses",
    "depreciation",
    "operating_profit",
    "interest_income",
    "interest_expense",
    "profit_before_tax",
    "tax",
    "net_profit",
    "property_plant_equipment",
    "intangible_assets",
    "inventory",
    "trade_receivables",
    "cash",
    "total_assets",
    "trade_payables",
    "accruals",
    "loans",
    "total_liabilities",
    "share_capital",
    "retained_earnings",
    "dividends",
    "total_equity",
    "unmapped",
]
