"""FRS 102 Section 1A accounting policy library — original authored wording.
Each policy: id, title, appliesWhen predicate, body. LLM may adapt narrative per client
profile but must NEVER insert monetary amounts (engine rejects digit strings except years).
Toggle per client; include only if appliesWhen passes."""
POLICIES = [
 {"id":"REVENUE","title":"Revenue",
  "appliesWhen":"REVENUE != 0",
  "body":"Revenue is recognised by applying the five-step model of Section 23 (as revised by the 2024 Periodic Review, effective for periods beginning on or after 1 January 2026): identify the contract, identify the performance obligations, determine the transaction price, allocate it to the performance obligations, and recognise revenue when (or as) each obligation is satisfied — i.e. when control of the goods or services transfers to the customer."},
 {"id":"FIXED_ASSETS","title":"Tangible fixed assets",
  "appliesWhen":"FIXED_ASSETS_NBV != 0",
  "body":"Tangible fixed assets are stated at cost less accumulated depreciation and any impairment losses. Cost includes directly attributable costs of acquisition and, where relevant, borrowing costs capitalised in accordance with the company's policy. Depreciation is charged on a straight-line basis over expected useful lives: plant and machinery {{life_plant}}, motor vehicles {{life_motor}}, fixtures and fittings {{life_ff}}, computer equipment {{life_it}}."},
 {"id":"INTANGIBLES","title":"Intangible assets",
  "appliesWhen":"INTANGIBLE_ASSETS != 0",
  "body":"Intangible assets are stated at cost less accumulated amortisation and impairment. Amortisation is charged over the asset's useful economic life. Development costs are capitalised only when the criteria for recognition are met and are amortised over the period of expected benefit."},
 {"id":"LEASES","title":"Leases",
  "appliesWhen":"HAS_LEASES == true",
  "body":"Leases are recognised on the balance sheet in accordance with Section 20 (as revised by the 2024 Periodic Review, aligned with IFRS 16): the lessee recognises a right-of-use asset and a lease liability at the lease commencement date, subsequently measuring the right-of-use asset at cost less accumulated depreciation and impairment and the liability at amortised cost. Short-term leases (12 months or less) and leases of low-value assets are exempt and are charged to profit or loss on a straight-line basis."},
 {"id":"STOCKS","title":"Stocks",
  "appliesWhen":"STOCKS != 0",
  "body":"Stocks are stated at the lower of cost and net realisable value, using the {{stock_method}} method. Cost includes materials, direct labour and an appropriate proportion of overheads."},
 {"id":"DEBTORS","title":"Debtors",
  "appliesWhen":"DEBTORS != 0",
  "body":"Short-term debtors are measured at transaction price less any impairment provision. A provision is recognised where there is objective evidence that the company will not be able to collect all amounts due."},
 {"id":"CREDITORS","title":"Creditors",
  "appliesWhen":"CREDITORS != 0",
  "body":"Short-term creditors are measured at the transaction price."},
 {"id":"BORROWING_COSTS","title":"Borrowing costs",
  "appliesWhen":"HAS_BORROWINGS == true",
  "body":"Borrowing costs are recognised in profit or loss in the period in which they are incurred, except where capitalised as part of the cost of a qualifying asset."},
 {"id":"TAXATION","title":"Taxation",
  "appliesWhen":"always",
  "body":"Current tax is measured at the amount expected to be paid, calculated at the rates enacted or substantively enacted at the reporting date. Deferred tax is recognised in respect of all timing differences at the reporting date, except where FRS 102 paragraphs 29.7 to 29.9 and 29.11A require otherwise. Deferred tax assets, including unrelieved tax losses, are recognised only to the extent that it is probable they will be recovered against the reversal of deferred tax liabilities or other future taxable profits. Deferred tax is measured at the tax rates and laws enacted or substantively enacted by the reporting date that are expected to apply when the timing differences reverse, and is not discounted."},
 {"id":"FOREIGN_CURRENCIES","title":"Foreign currencies",
  "appliesWhen":"HAS_FOREIGN == true",
  "body":"Transactions in foreign currencies are recorded at the rate ruling at the date of the transaction. Monetary assets and liabilities denominated in foreign currencies are retranslated at the rate ruling at the reporting date, with differences taken to profit or loss."},
 {"id":"EMPLOYEE_BENEFITS","title":"Employee benefits",
  "appliesWhen":"HAS_EMPLOYEES == true",
  "body":"Short-term employee benefits are recognised as an expense in the period in which the related service is received. Contributions to defined contribution pension schemes are charged to profit or loss as incurred."},
 {"id":"RELATED_PARTIES","title":"Related parties",
  "appliesWhen":"always",
  "body":"Related party transactions are disclosed in accordance with the requirements of company law and Section 1A of FRS 102."},
]
